service: finx-option-data

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: 'us-east-1'
  lambdaHashingVersion: 20201221
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
  environment:
    STAGE: ${sls:stage}

functions:
  fetch:
    events:
      - schedule: cron(* 13-20 ? * MON-FRI *)
    timeout: 40
    image:
      name: appimage
      command:
        - handler.handler_fetch_data
      entryPoint:
        - '/lambda-entrypoint.sh'
  move:
    events:
      - schedule: cron(15 17,20 ? * MON-FRI *)
    timeout: 40
    image:
      name: appimage
      command:
        - handler.handler_move_data_to_s3
      entryPoint:
        - '/lambda-entrypoint.sh'