service: finx-option-data

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: 'us-east-1'
  lambdaHashingVersion: 20201221
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
  environment:
    STAGE: ${sls:stage}

functions:
  fetch:
    memorySize: 256
    events:
      - schedule: cron(* 13-20 ? * MON-FRI *)
    timeout: 40
    image:
      name: appimage
      command:
        - handler.handler_fetch_data
      entryPoint:
        - '/lambda-entrypoint.sh'
  move:
    memorySize: 1024 # may need to adjust as
    events:
      - schedule: cron(15 13,14,15,16,17,18,19,20 ? * MON-FRI *)
    timeout: 40
    image:
      name: appimage
      command:
        - handler.handler_move_data_to_s3
      entryPoint:
        - '/lambda-entrypoint.sh'
  post_process_yesterday:
    memorySize: 4096
    events:
      - schedule: cron(15 0 ? * 2-6 *)
    timeout: 600
    image:
      name: appimage
      command:
        - handler_post_process.handler_post_process_yesterday
      entryPoint:
        - '/lambda-entrypoint.sh'
